name: "🐛 Bug report"
description: "Something isn’t working correctly."
labels: ["Must Have", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Please describe what went wrong.
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "What happened? Include screenshots if possible."
      placeholder: "When I click X, it should Y but instead it does Z..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "List the exact steps to trigger the issue."
  - type: input
    id: expected
    attributes:
      label: "Expected behavior"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - High
        - Medium
        - Low
