name: Deploy Astro (main + dev)

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./astro-portfolio-v2.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Choose target path
        id: choose
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "PATH=${{ secrets.VPS_PATH_MAIN }}" >> $GITHUB_OUTPUT
          else
            echo "PATH=${{ secrets.VPS_PATH_DEV }}" >> $GITHUB_OUTPUT
          fi

      - name: Add VPS host key (avoid interactive prompt)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy dist to VPS via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ steps.choose.outputs.PATH }}/dist/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
